/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#adaaaa",
        "on-secondary": "#002d46",
        "background": "#0e0e0e",
        "error-container": "#9f0519",
        "on-primary-container": "#003549",
        "on-tertiary-container": "#04005f",
        "surface-container": "#1a1919",
        "surface-container-high": "#201f1f",
        "tertiary-fixed": "#a6a9ff",
        "secondary-dim": "#22a6f1",
        "on-background": "#ffffff",
        "tertiary-container": "#878bf7",
        "secondary-fixed": "#a9d7ff",
        "tertiary": "#969aff",
        "on-tertiary-fixed-variant": "#272993",
        "surface-container-low": "#131313",
        "on-primary": "#003f57",
        "on-surface": "#ffffff",
        "outline-variant": "#494847",
        "on-secondary-container": "#f4f8ff",
        "primary": "#5dc9ff",
        "primary-container": "#00bdfd",
        "surface-tint": "#5dc9ff",
        "on-tertiary-fixed": "#040062",
        "inverse-surface": "#fcf8f8",
        "primary-dim": "#00afea",
        "secondary": "#37b1fd",
        "surface-container-highest": "#262626",
        "on-tertiary": "#0e0980",
        "on-primary-fixed-variant": "#003e56",
        "secondary-container": "#006495",
        "on-error": "#490006",
        "error-dim": "#d7383b",
        "on-secondary-fixed": "#003856",
        "surface-bright": "#2c2c2c",
        "on-secondary-fixed-variant": "#005580",
        "inverse-primary": "#00668a",
        "secondary-fixed-dim": "#89caff",
        "on-error-container": "#ffa8a3",
        "surface": "#0e0e0e",
        "primary-fixed-dim": "#00afea",
        "tertiary-fixed-dim": "#969aff",
        "surface-variant": "#262626",
        "surface-dim": "#0e0e0e",
        "surface-container-lowest": "#000000",
        "tertiary-dim": "#8f93ff",
        "outline": "#777575",
        "on-primary-fixed": "#001a27",
        "primary-fixed": "#00bdfd",
        "error": "#ff716c",
        "inverse-on-surface": "#565554",
      },
      fontFamily: {
        headline: ["Space Grotesk"],
        body: ["Inter"],
        label: ["Inter"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};
